spring:
  application:
    name: service8
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      serviceName: service8
      version: v1.0.0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${MCLUSTER_IP}:${MCLUSTER_PORT}/eureka
